{
  den,
  inputs,
  ...
}:
{
  imports = [ inputs.den.flakeModule ];

  # --- Host setup ---
  den.hosts.x86_64-linux.igloo.users.tux = { };

  den.aspects.igloo = {
    # User TODO: Remove for real host
    nixos.fileSystems."/".device = "/dev/no-boot";
    nixos.fileSystems."/".fsType = "auto";
    nixos.boot.loader.grub.enable = false;
  };

  den.aspects.tux = {
    includes = [ den.batteries.define-user ];
    user.description = "Bird";

    packages =
      { pkgs, ... }:
      {
        inherit (pkgs) cowsay;
      };

    tests =
      { tux, ... }:
      {
        test-tux-is-bird = {
          expr = tux.description;
          expected = "Bird";
        };
      };
  };

  # --- Flake-level aspects ---

  # Read flake-parts classes from foo aspect and its includes
  den.schema.flake-parts.includes = [ den.aspects.foo ];

  den.aspects.foo = {
    includes = [ den.aspects.bar ];

    treefmt.settings.on-unmatched = "warn";

    devshell.commands = [ { package = "cowsay"; } ];

    packages =
      { pkgs, ... }:
      {
        inherit (pkgs) htop;
      };
  };

  den.aspects.bar = {
    treefmt.programs.nixfmt.enable = true;

    tests.test-math-works = {
      expr = 22 * 2;
      expected = 44;
    };

    packages =
      { config, ... }:
      {
        write-files = config.files.writer.drv;
      };

    files =
      { pkgs, ... }:
      {
        files = [
          {
            path_ = "README.md";
            drv = pkgs.writeText "README.md" ''
              # Example Den custom classes for flake-parts modules and perSystem outputs.

              This example showcases Den forward classes for third-party flake-parts modules.

              This README is generated by `nix run .#write-files`.

              See den.nix and flake-parts.nix
            '';
          }
        ];
      };

    devshell =
      { pkgs, self', ... }:
      {
        commands = [
          {
            package = self'.packages.write-files;
          }
        ];
        packages = [
          pkgs.hello
        ];
      };
  };

  # --- Pipeline wiring ---

  # Enter flake-parts scope from flake-system.
  den.schema.flake-system.includes = [ den.policies.system-to-flake-parts ];

  # Exclude vanilla packages route — handled via flake-parts scope.
  den.schema.flake-system.excludes = [ den.policies.packages-to-flake ];
}
